### ISSUE TITLE
'ring' is not a task

### ISSUE THREAD

**Issue by tlehman** [caribou/caribou-docs#1]
I'm running Mac OS X 10.8.4, and using Leiningen 2.3.1 on Java 1.6.0_51, and when I cd to the root of the caribou-docs and run `lein ring server`, I get the error: 

```
'ring' is not a task. See 'lein help'.

Did you mean this?
         run
```

**Comment by prismofeverything** [comment]
Hello tlehman!  This project is no longer housing our docs, they have moved here:  

[Caribou docs](http://caribou.github.io/caribou/docs/outline.html)

Let me know if this is enough to get you started.

Regardless, I fixed your issue so if you do a pull you should be able to start the server.  It is a simple wiki built in Caribou so it could give you some ideas about how to build something non-trivial (though it is far from complete or polished).
